import { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		absolute: "",
		default: 'Next.js Tutorial - Codevolution',
		template: "%s | Codevolution",
	},
	description: 'Generated by Next.js',

};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en' suppressHydrationWarning={true}>
			<body>
				<header style={{ background: 'lightblue', padding: '1rem' }}>
					<p>Header</p>
				</header>
				{children}
				<footer style={{ background: 'ghostwhite', padding: '1rem' }}>
					<p>Footer</p>
				</footer>
			</body>
		</html>
	);
}
